Feat: `use_debounce`
DioxusLabs/sdk pull request #37
Opened 2024-04-27 21:58 UTC by DogeDark

Adds a `use_debounce` hook.

2024-04-27 22:00 UTC, DogeDark commented
@marc2332 I took some inspiration from your debouncer hook. This one doesn't use the `debounce` crate though.

2024-04-27 22:04 UTC, marc2332 requested changes

2024-04-27 22:04 UTC, marc2332 commented on sdk/src/utils/timing/debounce.rs
I am not entirely sure about this implementation

1. First call runs instantly
2. Following calls do not get debounced, just stacked in top of each other

note: I have not tried running, I am just looking at the code

2024-04-27 22:06 UTC, marc2332 commented on sdk/src/utils/timing/debounce.rs
I can see you took some inspiration from https://github.com/marc2332/valin/blob/main/src/hooks/use_debouncer.rs btw :trollface:

2024-04-27 22:07 UTC, marc2332 commented on sdk/src/utils/timing/debounce.rs
Just saw your message above hah

2024-04-27 22:09 UTC, DogeDark commented on sdk/src/utils/timing/debounce.rs
The ``.recv()`` should be run rather quickly, clearing the queue whether or not a debounce ran. It worked fine during testing but that was with a button click. Perhaps something faster could cause an issue? 

Planning to use this with the ``use_window_size`` for the component library so that could be a good benchmark to see if there are any issues.

2024-04-27 22:22 UTC, marc2332 commented on sdk/src/utils/timing/debounce.rs
The issue here is that new callbacks should make the old ones not run at all, and that is not happening,

if you called the callback 2 times very fast:

1. First callback would get called instantly (this should not happen, there should be a delay to see if there is a newer callback until the delay finishes)
2. Second callback would not get called ever (this is wrong, the callback should be called after the delay has finished and should also stop the first callback from ever running)

But again, I am just saying this from what I can see in the code, I have not run it yet

2024-04-27 22:23 UTC, marc2332 commented on sdk/src/utils/timing/debounce.rs
I would have just used the debounced crate tbh haha

2024-04-27 22:31 UTC, DogeDark commented on sdk/src/utils/timing/debounce.rs
> the callback should be called after the delay has finished

There are some cases where I can see this behavior being unwarranted and I was designing this one to avoid that. It turns out for my use-case, I do need that to happen. I think we'll just use your existing implementation with the debounced crate lol

2024-04-27 22:35 UTC, DogeDark commented on sdk/src/utils/timing/debounce.rs
`debounced` calls it a leading debounce. That's what I (think??) I was trying to implement:

![image](https://github.com/DioxusLabs/sdk/assets/30190859/5ca17d13-d82b-467a-b34a-e33afa8b0b62)

2024-04-27 22:37 UTC, marc2332 commented on sdk/src/utils/timing/debounce.rs
I think most people want trailing, I didn't even know there was leading debouncing 🤔 

From what I understand:
- leading: First take priority
- trailing: Last take priority

2024-04-27 22:45 UTC, DogeDark commented on sdk/src/utils/timing/debounce.rs
Uh oh `debounced` doesn't work on wasm. 😕

2024-04-27 23:14 UTC, DogeDark commented on sdk/src/utils/timing/debounce.rs
What about this implementation?

2024-04-28 07:52 UTC, marc2332 requested changes

2024-04-28 07:52 UTC, marc2332 commented on sdk/src/utils/timing/debounce.rs
> +                    if let Some(task) = current_task {
You probably want:
```suggestion
                    if let Some(task) = current_task.take() {
```

2024-04-28 07:54 UTC, marc2332 commented on sdk/src/utils/timing/debounce.rs
Seems correct, although it would be nice if we could pass some sort of state to the callback from when it's called

example: https://www.npmjs.com/package/use-debounce#debounced-callbacks

2024-05-03 16:21 UTC, marc2332 commented on sdk/src/utils/timing/debounce.rs
> +pub fn use_debounce<T: Clone>(
Why does `T` need to be `Clone`?

2024-05-03 16:32 UTC, marc2332 requested changes

2024-05-03 16:32 UTC, marc2332 commented on sdk/src/utils/timing/debounce.rs
> +}
```suggestion
#[derive(Copy, PartialEq)]
pub struct UseDebounce<T: 'static> {
    sender: Signal<Sender<T>>,
}

impl<T> Clone for UseDebounce<T> {
    fn clone(&self) -> Self {
        *self
    }
}
```

2024-05-03 16:45 UTC, marc2332 requested changes

2024-05-03 16:45 UTC, marc2332 commented on sdk/src/utils/timing/debounce.rs
> +}
```suggestion
pub struct UseDebounce<T: 'static> {
    sender: Signal<Sender<T>>,
}

impl<T> PartialEq for UseDebounce<T> {
    fn eq(&self, other: &Self) -> bool {
        self == other
    }
}
```

2024-05-03 16:56 UTC, marc2332 approved these changes
🔥

2024-05-03 16:59 UTC, merged